insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (1, 'Errick Sharland', '45496542185', 'esharland0@google.nl', 'Radio And Television Broadcasting And Communications Equipment', 'FL', 'Jacksonville', 2);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (2, 'Nealon Formoy', '42040998263', 'nformoy1@sina.com.cn', 'n/a', 'CA', 'Long Beach', 1);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (3, 'Fifi Jorge', '05406238606', 'fjorge2@xinhuanet.com', 'n/a', 'FL', 'Orlando', 1);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (4, 'Inness Brewster', '59510393164', 'ibrewster3@theglobeandmail.com', 'Major Pharmaceuticals', 'ID', 'Boise', 4);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (5, 'Olympie Hullbrook', '00103223217', 'ohullbrook4@mac.com', 'EDP Services', 'KS', 'Kansas City', 3);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (6, 'Pall Lecointe', '67695679164', 'plecointe5@people.com.cn', 'Investment Bankers/Brokers/Service', 'NY', 'Buffalo', 4);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (7, 'Joe Latus', '19977882936', 'jlatus6@home.pl', 'n/a', 'TX', 'Dallas', 6);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (8, 'Fons Powlesland', '70215880996', 'fpowlesland7@columbia.edu', 'Finance: Consumer Services', 'PA', 'Philadelphia', 1);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (9, 'Linc Echalier', '61236917713', 'lechalier8@stanford.edu', 'Major Chemicals', 'FL', 'Sarasota', 6);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (10, 'Joellyn Swatton', '56639449258', 'jswatton9@washington.edu', 'Packaged Foods', 'TX', 'Houston', 3);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (11, 'Camila Troke', '14896019939', 'ctrokea@oakley.com', 'Natural Gas Distribution', 'CA', 'Santa Ana', 1);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (12, 'Sandro Kohring', '34514548387', 'skohringb@myspace.com', 'n/a', 'TX', 'Houston', 4);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (13, 'Terrance Athow', '39522551585', 'tathowc@wired.com', 'Aerospace', 'FL', 'Miami', 3);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (14, 'Con Knoble', '85158808799', 'cknobled@so-net.ne.jp', 'n/a', 'MA', 'Waltham', 6);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (15, 'Jacky Crush', '55102065476', 'jcrushe@icio.us', 'Real Estate', 'TX', 'Amarillo', 6);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (16, 'Nelly Bowra', '08554220739', 'nbowraf@goo.ne.jp', 'Air Freight/Delivery Services', 'MN', 'Monticello', 5);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (17, 'Basile Filinkov', '19863420798', 'bfilinkovg@indiatimes.com', 'Real Estate Investment Trusts', 'WA', 'Tacoma', 6);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (18, 'Queenie Dudgeon', '11343794948', 'qdudgeonh@ucoz.ru', 'Property-Casualty Insurers', 'NY', 'Syracuse', 5);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (19, 'Odelle Proudlock', '67419300731', 'oproudlocki@creativecommons.org', 'Precious Metals', 'FL', 'Fort Lauderdale', 1);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (20, 'Brett Grogono', '32025891786', 'bgrogonoj@princeton.edu', 'n/a', 'NY', 'New York City', 1);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (21, 'Anderson Trevon', '05842025285', 'atrevonk@senate.gov', 'Major Banks', 'TX', 'Houston', 2);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (22, 'York Bednell', '63934405900', 'ybednelll@bloglines.com', 'Hotels/Resorts', 'CA', 'San Diego', 3);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (23, 'Sabrina Pattison', '77849613223', 'spattisonm@t.co', 'Clothing/Shoe/Accessory Stores', 'NY', 'Flushing', 1);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (24, 'Willette Tarry', '35986067659', 'wtarryn@google.co.jp', 'n/a', 'DE', 'Wilmington', 5);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (25, 'Galen Uc', '32427001163', 'guco@blogs.com', 'n/a', 'PA', 'York', 2);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (26, 'Kiah Minifie', '34658912652', 'kminifiep@ca.gov', 'Auto Parts:O.E.M.', 'TX', 'Austin', 2);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (27, 'Mikey Kasbye', '23778945974', 'mkasbyeq@economist.com', 'Telecommunications Equipment', 'TX', 'Austin', 6);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (28, 'Evangelin Esche', '94808206885', 'eescher@sitemeter.com', 'Major Pharmaceuticals', 'FL', 'Miami', 6);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (29, 'Dev Barkess', '36305805032', 'dbarkesss@ustream.tv', 'Major Chemicals', 'FL', 'Orlando', 2);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (30, 'Richmound Olivie', '20456167455', 'roliviet@vk.com', 'Other Consumer Services', 'FL', 'Orlando', 4);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (31, 'Carri Andriveau', '72731531564', 'candriveauu@kickstarter.com', 'EDP Services', 'FL', 'Melbourne', 2);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (32, 'Bil Cloney', '99338727777', 'bcloneyv@sourceforge.net', 'n/a', 'NY', 'New York City', 2);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (33, 'Hieronymus Shoebrook', '96027804667', 'hshoebrookw@bloglines.com', 'Television Services', 'CA', 'San Jose', 2);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (34, 'Tuck Gamlen', '56674315760', 'tgamlenx@usgs.gov', 'n/a', 'CA', 'Visalia', 4);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (35, 'Marijo Gromley', '43844657568', 'mgromleyy@nih.gov', 'Semiconductors', 'MA', 'Watertown', 2);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (36, 'Giacobo Everett', '84087217145', 'geverettz@google.cn', 'Movies/Entertainment', 'NY', 'Albany', 3);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (37, 'Wrennie Chimenti', '42855619893', 'wchimenti10@yolasite.com', 'Major Pharmaceuticals', 'CA', 'Corona', 2);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (38, 'Dorita Hearns', '22726457434', 'dhearns11@pbs.org', 'Major Banks', 'MN', 'Minneapolis', 5);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (39, 'Florie Sayton', '37908687695', 'fsayton12@huffingtonpost.com', 'Real Estate Investment Trusts', 'FL', 'Kissimmee', 3);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (40, 'Tiffi Attoc', '11463987772', 'tattoc13@ftc.gov', 'Industrial Machinery/Components', 'CA', 'Los Angeles', 6);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (41, 'Camilla Buyers', '28920026590', 'cbuyers14@woothemes.com', 'Business Services', 'NY', 'Albany', 5);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (42, 'Erwin Buttwell', '82812876456', 'ebuttwell15@goo.ne.jp', 'Telecommunications Equipment', 'PA', 'Pittsburgh', 4);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (43, 'Hilario Diffley', '67229547451', 'hdiffley16@dot.gov', 'Medical/Dental Instruments', 'TX', 'Houston', 2);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (44, 'Catie Bloys', '31915161468', 'cbloys17@unblog.fr', 'n/a', 'FL', 'Boca Raton', 1);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (45, 'Reginauld McTrustey', '43069998233', 'rmctrustey18@nps.gov', 'Natural Gas Distribution', 'HI', 'Honolulu', 2);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (46, 'Odetta Dod', '69228257686', 'odod19@cpanel.net', 'Diversified Financial Services', 'FL', 'Tampa', 5);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (47, 'Lukas Corbie', '63418409111', 'lcorbie1a@theatlantic.com', 'n/a', 'NY', 'New York City', 3);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (48, 'Nolie Risman', '83350140590', 'nrisman1b@canalblog.com', 'Computer Software: Prepackaged Software', 'FL', 'Gainesville', 5);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (49, 'Ninon Oxenbury', '00630702962', 'noxenbury1c@trellian.com', 'Oil & Gas Production', 'FL', 'Tampa', 3);
insert into Cliente (id, nome, telefone, email, segmento, uf, cidade, etapa_id) values (50, 'Barbabas Tartt', '70746534500', 'btartt1d@addtoany.com', 'n/a', 'FL', 'Gainesville', 2);
