insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (15, 45, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (29, 43, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (38, 24, 2, 'Não quis perder tempo em um evento da empresa');
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (15, 25, 2, 'Não achei necessário comparecer');
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (36, 48, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (40, 25, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (13, 22, 2, 'Não quis me expor em um evento da empresa');
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (49, 13, 2, 'Não quis me envolver com colegas de trabalho');
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (25, 24, 1, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (44, 4, 1, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (12, 8, 2, 'Não quis me expor em um evento da empresa');
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (14, 43, 2, 'Não quis me envolver em confraternizações');
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (40, 15, 1, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (43, 18, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (27, 3, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (26, 40, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (47, 38, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (12, 26, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (22, 45, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (42, 2, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (2, 39, 1, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (6, 39, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (2, 34, 1, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (35, 49, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (48, 4, 2, 'Não quis participar de atividades em grupo');
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (2, 45, 1, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (46, 15, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (36, 21, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (9, 6, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (33, 4, 2, 'Não me identifiquei com o tema do evento');
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (4, 12, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (34, 40, 2, 'Esqueci do evento');
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (45, 38, 1, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (14, 2, 1, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (11, 11, 1, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (2, 38, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (12, 14, 2, 'Não consegui me organizar a tempo');
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (19, 41, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (45, 46, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (4, 35, 2, 'Não me interessei pelo evento');
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (50, 30, 2, 'Não recebi o convite');
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (28, 23, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (3, 18, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (5, 33, 1, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (24, 7, 1, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (10, 31, 2, 'Não consegui me organizar a tempo');
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (48, 39, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (24, 5, 3, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (8, 10, 1, null);
insert into Participacao (colaborador_id, evento_id, status_participacao_id, justificativa) values (15, 49, 1, null);
