spring.application.name=banco

#conexão
spring.datasource.url=jdbc:mysql://localhost:3306/nu
spring.datasource.username=root
spring.datasource.password=rafa

#comando
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql: true

#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql=trace